/**
 * Arduino (C++) target — Arduino Mega-style pin mapping.
 *   DO0..DO7  → digital 2..9
 *   DI0..DI7  → digital 22..29
 *   AI0..AI7  → analog A0..A7
 *   AO0..AO3  → PWM pins 5,6,9,10   (analogWrite 0..255)
 */

import { type Emitter, walkWorkspace, indentBody } from './walker';
import type { WorkspaceJSON } from './types';

const INDENT = '  ';

function arduinoPin(channel: string): number {
  const m = /^([A-Z]+)(\d+)$/.exec(channel);
  if (!m) return -1;
  const [, kind, idxStr] = m;
  const i = Number(idxStr);
  switch (kind) {
    case 'DO': return 2 + i;       // 2..9
    case 'DI': return 22 + i;      // 22..29
    case 'AI': return 14 + i;      // A0..A7 are pins 14..21 internally; analogRead accepts A0..A7 macros too
    case 'AO': return [5, 6, 9, 10][i] ?? 5;
  }
  return -1;
}
function arduinoPinLabel(channel: string): string {
  const p = arduinoPin(channel);
  if (channel.startsWith('AI')) return `A${channel.slice(2)}`;
  return String(p);
}

function pinModeFor(channel: string): string | null {
  if (channel.startsWith('DO') || channel.startsWith('AO')) return `pinMode(${arduinoPinLabel(channel)}, OUTPUT);`;
  if (channel.startsWith('DI')) return `pinMode(${arduinoPinLabel(channel)}, INPUT);`;
  return null; // analog input doesn't need pinMode
}

const arduinoEmitter: Emitter = {
  indent: INDENT,

  preamble(used, vars) {
    const header = [
      '// ============================================================',
      '// Generated by Nexys Blockly Studio',
      '// Target: Arduino (UNO / Mega) — C++ with Arduino core',
      '// ============================================================',
      '',
      '#include <Arduino.h>',
      '',
    ];
    const varSection = vars.length
      ? ['// User-defined variables (global)', ...vars.map(v => `float ${v} = 0.0f;`), '']
      : [];
    return [...header, ...varSection].join('\n');
  },

  assemble({ varDecls, procDefs, loopCallbacks, mainStatements }) {
    // Build setup() — collect pinMode for every channel referenced
    const setupBody: string[] = ['Serial.begin(115200);'];
    // (varDecls go global, but if any setup-time inits are present they appear here too)

    // Loop callback definitions
    const callbacks = loopCallbacks.map(({ name, body }) =>
      `void ${name}() {\n${indentBody(body, INDENT)}\n}`
    ).join('\n\n');

    // loop() scheduler with last-tick tracking per callback
    const tickVars = loopCallbacks.map(c =>
      `unsigned long _last_${c.name} = 0;\nconst unsigned long _ival_${c.name} = ${c.intervalMs};`
    ).join('\n');
    const tickChecks = loopCallbacks.map(c =>
      `${INDENT}if (now - _last_${c.name} >= _ival_${c.name}) { _last_${c.name} = now; ${c.name}(); }`
    ).join('\n');

    const setupSrc = [
      `void setup() {`,
      ...setupBody.map(l => INDENT + l),
      ...(mainStatements ? [INDENT + '// One-shot startup statements:', indentBody(mainStatements, INDENT)] : []),
      '}',
    ].join('\n');

    const loopSrc = loopCallbacks.length === 0
      ? `void loop() {\n${INDENT}// no loop_every blocks\n${INDENT}delay(100);\n}`
      : `void loop() {\n${INDENT}unsigned long now = millis();\n${tickChecks}\n}`;

    return [
      procDefs,
      tickVars,
      callbacks,
      setupSrc,
      loopSrc,
    ].filter(Boolean).join('\n\n') + '\n';
  },

  // ── statements ──
  delay: (ms) => `delay(${ms});`,
  repeat: (n, body) =>
    `for (int _i = 0; _i < ${n}; _i++) {\n${indentBody(body, INDENT)}\n}`,
  ifThen: (cond, then, els) => {
    let out = `if (${cond}) {\n${indentBody(then, INDENT)}\n}`;
    if (els) out += ` else {\n${indentBody(els, INDENT)}\n}`;
    return out;
  },
  waitUntil: (cond) =>
    `while (!(${cond})) { delay(20); /* poll */ }`,

  doWrite: (ch, lvl) =>
    `digitalWrite(${arduinoPinLabel(ch)}, ${lvl});  // ${ch}`,
  aoWrite: (ch, v) =>
    `analogWrite(${arduinoPinLabel(ch)}, (int)constrain((${v}) * 51.0f, 0, 255));  // ${ch} (0..5V → 0..255 PWM)`,
  ifChannelThen: (ch, lvl, body) => {
    const cond = lvl === 'HIGH'
      ? `digitalRead(${arduinoPinLabel(ch)}) == HIGH`
      : `digitalRead(${arduinoPinLabel(ch)}) == LOW`;
    return `if (${cond}) {  // ${ch}\n${indentBody(body, INDENT)}\n}`;
  },

  logTdms: (name, v) =>
    `Serial.print(F("TDMS,${name},"));  Serial.println(${v});  // log entry`,
  publishMqtt: (topic, payload) =>
    `// TODO: MQTT publish to "${topic}" — wire up PubSubClient.\n` +
    `Serial.print(F("MQTT[${topic}] "));  Serial.println(${payload});`,
  alarm: (via, msg) =>
    `Serial.print(F("ALARM[${via}] "));  Serial.println(F(${JSON.stringify(msg)}));`,
  bitResult: (v, val) =>
    `Serial.print(F("BIT ${v} ="));  Serial.println(${val});`,

  varSet: (name, v) => `${name} = ${v};`,
  procCall: (name) => `${name}();`,

  // ── expressions ──
  aiRead: (ch) =>
    `((float)analogRead(${arduinoPinLabel(ch)}) * (5.0f / 1023.0f))  /* ${ch} */`,
  diRead: (ch) =>
    `(digitalRead(${arduinoPinLabel(ch)}) == HIGH)  /* ${ch} */`,
  sensorRead: (sensor, ch) =>
    `nexys_sensor_${sensor}(${ch})  /* TODO: link real driver */`,

  scaleLinear: (x, a, b) => `((${a}) * (${x}) + (${b}))`,
  computeRms: (sig, n) => `nexys_rms(${sig}, ${n})  /* helper */`,
  lpf: (sig, hz) => `nexys_lpf(${sig}, ${hz})  /* helper */`,
  thresholdCheck: (v, lo, hi) => `((${v}) >= (${lo}) && (${v}) <= (${hi}))`,

  num: (n) => Number.isInteger(n) ? `${n}` : `${n.toFixed(3)}f`,
  bool: (v) => v ? 'true' : 'false',
  text: (s) => JSON.stringify(s),
  varGet: (name) => name,

  arith: (op, a, b) => {
    switch (op) {
      case 'MINUS':    return `((${a}) - (${b}))`;
      case 'MULTIPLY': return `((${a}) * (${b}))`;
      case 'DIVIDE':   return `((${a}) / (${b}))`;
      case 'POWER':    return `pow(${a}, ${b})`;
      default:         return `((${a}) + (${b}))`;
    }
  },
  compare: (op, a, b) => {
    const map: Record<string, string> = { EQ: '==', NEQ: '!=', LT: '<', LTE: '<=', GT: '>', GTE: '>=' };
    return `((${a}) ${map[op] ?? '=='} (${b}))`;
  },
  logicOp: (op, a, b) => `((${a}) ${op === 'OR' ? '||' : '&&'} (${b}))`,

  procDef: (name, body) =>
    `void ${name}() {\n${indentBody(body, INDENT)}\n}`,
};

export function generateArduino(json: WorkspaceJSON): string {
  return walkWorkspace(json, arduinoEmitter);
}
