/**
 * Python targets — Raspberry Pi and NVIDIA Jetson Orin.
 *
 * Both run our `nexys` SDK on top of platform-specific GPIO backends:
 *   - RPi:    nexys backend over RPi.GPIO + spidev
 *   - Jetson: nexys backend over Jetson.GPIO (compatible API)
 *
 * Reuses the Blockly pythonGenerator we already configured — only the
 * preamble + init line differ between platforms.
 */

import { buildFullPython } from '@/lib/blockly/python-generator';
import type { WorkspaceJSON } from './types';

export type PythonVariant = 'rpi' | 'jetson';

const HEADERS: Record<PythonVariant, string> = {
  rpi: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: Raspberry Pi 4B / 5 with Nexys-RPi-Mod HAT',
    '# Runtime: Python 3.11 + nexys-sdk (RPi.GPIO backend)',
    '# ============================================================',
    'import nexys',
    'nexys.init(target="rpi-4b", agent="nexys-agent")',
    '',
  ].join('\n'),

  jetson: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NVIDIA Jetson Orin Nano + Nexys-Jetson-Mod',
    '# Runtime: Python 3.11 + nexys-sdk (Jetson.GPIO backend)',
    '#         Optional CUDA acceleration for signal processing',
    '# ============================================================',
    'import nexys',
    'import Jetson.GPIO as _gpio   # exposed for direct CUDA-aware pipelines',
    'nexys.init(target="jetson-orin-nano", gpio_backend=_gpio)',
    '',
  ].join('\n'),
};

export function generatePython(
  variant: PythonVariant,
  workspace: unknown,
  pythonGenerator: any,
  moduleDefs = '',
): string {
  // We reuse the existing buildFullPython (which already wraps in def main()
  // + entry guard). Just swap out the standard PYTHON_HEADER for our
  // target-specific banner, and inject module (Sub-VI) defs ahead of main().
  const full = buildFullPython(pythonGenerator, workspace);
  // buildFullPython always begins with the default PYTHON_HEADER; replace
  // up to the first blank line after `import nexys` with our banner.
  const splitIdx = full.indexOf('\n\n');
  const rest = splitIdx === -1 ? full : full.slice(splitIdx + 2);
  return HEADERS[variant] + (moduleDefs || '') + rest;
}

// generate-without-pythonGenerator stubs for type compatibility with TargetSpec
export function generateRpi(json: WorkspaceJSON, pyGen?: any): string {
  if (!pyGen) return HEADERS.rpi + '# (workspace generator not ready)\n';
  return generatePython('rpi', json, pyGen);
}
export function generateJetson(json: WorkspaceJSON, pyGen?: any): string {
  if (!pyGen) return HEADERS.jetson + '# (workspace generator not ready)\n';
  return generatePython('jetson', json, pyGen);
}
