/**
 * NI Python targets — PXIe, CompactRIO, CompactDAQ.
 *
 * All run our `nexys` SDK on top of the NI-DAQmx backend. Reuses the Blockly
 * pythonGenerator we already configured — only the preamble + init line differ
 * between instruments.
 */

import { buildFullPython } from '@/lib/blockly/python-generator';

export type PythonVariant = 'ni_pxie' | 'ni_crio' | 'ni_cdaq';

const HEADERS: Record<PythonVariant, string> = {
  ni_pxie: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI PXIe (PXIe-1092 chassis + PXIe-6363 DAQ)',
    '# Runtime: Python 3.11 + nidaqmx · nexys-sdk NI backend',
    '# ============================================================',
    'import nidaqmx                       # NI-DAQmx Python API',
    'from nidaqmx.constants import LineGrouping',
    'import nexys',
    'nexys.init(target="ni-pxie", backend="nidaqmx", device="PXI1Slot2")',
    '# DAQmx can also stream natively: task.in_stream.configure_logging(',
    '#     "nexys_run.tdms", LoggingMode.LOG_AND_READ)',
    'nexys.tdms_open("nexys_run.tdms")   # log_tdms() writes a real TDMS 2.0 file',
    '',
  ].join('\n'),

  ni_crio: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI CompactRIO (cRIO-9045 + C-Series modules)',
    '# Runtime: Python 3.11 on NI Linux RT · nidaqmx · nexys-sdk',
    '# ============================================================',
    'import nidaqmx',
    'import nexys',
    'nexys.init(target="ni-crio", backend="nidaqmx", device="cRIO1")',
    'nexys.tdms_open("nexys_run.tdms")   # log_tdms() writes a real TDMS 2.0 file',
    '',
  ].join('\n'),

  ni_cdaq: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI CompactDAQ (cDAQ-9178 + C-Series modules)',
    '# Runtime: Python 3.11 + nidaqmx · nexys-sdk NI backend',
    '# ============================================================',
    'import nidaqmx',
    'import nexys',
    'nexys.init(target="ni-cdaq", backend="nidaqmx", device="cDAQ1")',
    'nexys.tdms_open("nexys_run.tdms")   # log_tdms() writes a real TDMS 2.0 file',
    '',
  ].join('\n'),
};

export function generatePython(
  variant: PythonVariant,
  workspace: unknown,
  pythonGenerator: any,
  moduleDefs = '',
): string {
  // We reuse the existing buildFullPython (which already wraps in def main()
  // + entry guard). Just swap out the standard PYTHON_HEADER for our
  // target-specific banner, and inject module (Sub-VI) defs ahead of main().
  const full = buildFullPython(pythonGenerator, workspace);
  // buildFullPython always begins with the default PYTHON_HEADER; replace
  // up to the first blank line after `import nexys` with our banner.
  const splitIdx = full.indexOf('\n\n');
  const rest = splitIdx === -1 ? full : full.slice(splitIdx + 2);
  return HEADERS[variant] + (moduleDefs || '') + rest;
}
