/**
 * Python targets — Raspberry Pi and NVIDIA Jetson Orin.
 *
 * Both run our `nexys` SDK on top of platform-specific GPIO backends:
 *   - RPi:    nexys backend over RPi.GPIO + spidev
 *   - Jetson: nexys backend over Jetson.GPIO (compatible API)
 *
 * Reuses the Blockly pythonGenerator we already configured — only the
 * preamble + init line differ between platforms.
 */

import { buildFullPython } from '@/lib/blockly/python-generator';
import type { WorkspaceJSON } from './types';

export type PythonVariant = 'rpi' | 'jetson' | 'ni_pxie' | 'ni_crio' | 'ni_cdaq';

const HEADERS: Record<PythonVariant, string> = {
  rpi: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: Raspberry Pi 4B / 5 with Nexys-RPi-Mod HAT',
    '# Runtime: Python 3.11 + nexys-sdk (RPi.GPIO backend)',
    '# ============================================================',
    'import nexys',
    'from nptdms import TdmsWriter   # real TDMS 2.0 file writer',
    'nexys.init(target="rpi-4b", agent="nexys-agent")',
    'nexys.tdms_open("nexys_run.tdms", writer=TdmsWriter)   # log_tdms() streams real .tdms',
    '',
  ].join('\n'),

  jetson: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NVIDIA Jetson Orin Nano + Nexys-Jetson-Mod',
    '# Runtime: Python 3.11 + nexys-sdk (Jetson.GPIO backend)',
    '#         Optional CUDA acceleration for signal processing',
    '# ============================================================',
    'import nexys',
    'import Jetson.GPIO as _gpio   # exposed for direct CUDA-aware pipelines',
    'from nptdms import TdmsWriter',
    'nexys.init(target="jetson-orin-nano", gpio_backend=_gpio)',
    'nexys.tdms_open("nexys_run.tdms", writer=TdmsWriter)   # log_tdms() streams real .tdms',
    '',
  ].join('\n'),

  ni_pxie: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI PXIe (PXIe-1092 chassis + PXIe-6363 DAQ)',
    '# Runtime: Python 3.11 + nidaqmx · nexys-sdk NI backend',
    '# ============================================================',
    'import nidaqmx                       # NI-DAQmx Python API',
    'from nidaqmx.constants import LineGrouping, LoggingMode, LoggingOperation',
    'import nexys',
    'nexys.init(target="ni-pxie", backend="nidaqmx", device="PXI1Slot2")',
    '# DAQmx streams a real .tdms directly: task.in_stream.configure_logging(',
    '#     "nexys_run.tdms", LoggingMode.LOG_AND_READ, operation=LoggingOperation.CREATE_OR_REPLACE)',
    'nexys.tdms_open("nexys_run.tdms", backend="daqmx")   # log_tdms() → native TDMS',
    '',
  ].join('\n'),

  ni_crio: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI CompactRIO (cRIO-9045 + C-Series modules)',
    '# Runtime: Python 3.11 on NI Linux RT · nidaqmx · nexys-sdk',
    '# ============================================================',
    'import nidaqmx',
    'from nidaqmx.constants import LoggingMode, LoggingOperation',
    'import nexys',
    'nexys.init(target="ni-crio", backend="nidaqmx", device="cRIO1")',
    'nexys.tdms_open("nexys_run.tdms", backend="daqmx")   # log_tdms() → native TDMS',
    '',
  ].join('\n'),

  ni_cdaq: [
    '# ============================================================',
    '# Generated by Nexys Blockly Studio',
    '# Target: NI CompactDAQ (cDAQ-9178 + C-Series modules)',
    '# Runtime: Python 3.11 + nidaqmx · nexys-sdk NI backend',
    '# ============================================================',
    'import nidaqmx',
    'from nidaqmx.constants import LoggingMode, LoggingOperation',
    'import nexys',
    'nexys.init(target="ni-cdaq", backend="nidaqmx", device="cDAQ1")',
    'nexys.tdms_open("nexys_run.tdms", backend="daqmx")   # log_tdms() → native TDMS',
    '',
  ].join('\n'),
};

export function generatePython(
  variant: PythonVariant,
  workspace: unknown,
  pythonGenerator: any,
  moduleDefs = '',
): string {
  // We reuse the existing buildFullPython (which already wraps in def main()
  // + entry guard). Just swap out the standard PYTHON_HEADER for our
  // target-specific banner, and inject module (Sub-VI) defs ahead of main().
  const full = buildFullPython(pythonGenerator, workspace);
  // buildFullPython always begins with the default PYTHON_HEADER; replace
  // up to the first blank line after `import nexys` with our banner.
  const splitIdx = full.indexOf('\n\n');
  const rest = splitIdx === -1 ? full : full.slice(splitIdx + 2);
  return HEADERS[variant] + (moduleDefs || '') + rest;
}

// generate-without-pythonGenerator stubs for type compatibility with TargetSpec
export function generateRpi(json: WorkspaceJSON, pyGen?: any): string {
  if (!pyGen) return HEADERS.rpi + '# (workspace generator not ready)\n';
  return generatePython('rpi', json, pyGen);
}
export function generateJetson(json: WorkspaceJSON, pyGen?: any): string {
  if (!pyGen) return HEADERS.jetson + '# (workspace generator not ready)\n';
  return generatePython('jetson', json, pyGen);
}
