/**
 * STM32 (C, HAL) target — STM32F4 Nucleo-style mapping.
 *   DO0..DO7  → GPIOA pin 0..7
 *   DI0..DI7  → GPIOB pin 0..7
 *   AI0..AI7  → ADC1 channels 0..7 (read via HAL_ADC_PollForConversion)
 *   AO0..AO3  → DAC channels (only 2 on most parts; rest emitted as PWM TIM3)
 */

import { type Emitter, walkWorkspace, indentBody } from './walker';
import type { WorkspaceJSON } from './types';

const INDENT = '  ';

function stmPin(channel: string): { port: string; pin: number } | null {
  const m = /^([A-Z]+)(\d+)$/.exec(channel);
  if (!m) return null;
  const [, kind, idxStr] = m;
  const i = Number(idxStr);
  if (kind === 'DO') return { port: 'GPIOA', pin: i };
  if (kind === 'DI') return { port: 'GPIOB', pin: i };
  return null;
}

const stm32Emitter: Emitter = {
  indent: INDENT,

  preamble(used, vars) {
    return [
      '/* ===========================================================',
      ' * Generated by Nexys Blockly Studio',
      ' * Target: STM32 (F4 Nucleo) — HAL drivers',
      ' * Pin map: DO=GPIOA, DI=GPIOB, AI=ADC1, AO=DAC1/2 + TIM PWM',
      ' * =========================================================== */',
      '',
      '#include "main.h"',
      '#include "stm32f4xx_hal.h"',
      '#include <stdio.h>',
      '',
      'extern ADC_HandleTypeDef hadc1;',
      'extern DAC_HandleTypeDef hdac;',
      'extern UART_HandleTypeDef huart2;',
      '',
      'static float nexys_rms(float x, int n) { (void)n; return x * 0.707f; }',
      'static float nexys_lpf(float x, float hz) { (void)hz; return x * 0.95f; }',
      '',
      vars.length ? '/* User-defined globals */' : '',
      ...vars.map(v => `static float ${v} = 0.0f;`),
      vars.length ? '' : '',
    ].filter(Boolean).join('\n');
  },

  assemble({ varDecls, procDefs, loopCallbacks, mainStatements }) {
    const callbacks = loopCallbacks.map(({ name, body }) =>
      `static void ${name}(void) {\n${indentBody(body, INDENT)}\n}`
    ).join('\n\n');

    const tickState = loopCallbacks.map(c =>
      `static uint32_t _last_${c.name} = 0;\nstatic const uint32_t _ival_${c.name} = ${c.intervalMs};`
    ).join('\n');
    const tickDispatch = loopCallbacks.map(c =>
      `${INDENT}${INDENT}if (now - _last_${c.name} >= _ival_${c.name}) { _last_${c.name} = now; ${c.name}(); }`
    ).join('\n');

    const startup = mainStatements
      ? `${INDENT}/* One-shot startup statements */\n${indentBody(mainStatements, INDENT)}\n`
      : '';

    const mainSrc = [
      'int main(void) {',
      `${INDENT}HAL_Init();`,
      `${INDENT}SystemClock_Config();`,
      `${INDENT}MX_GPIO_Init();`,
      `${INDENT}MX_ADC1_Init();`,
      `${INDENT}MX_DAC_Init();`,
      `${INDENT}MX_USART2_UART_Init();`,
      '',
      startup,
      `${INDENT}while (1) {`,
      `${INDENT}${INDENT}uint32_t now = HAL_GetTick();`,
      tickDispatch || `${INDENT}${INDENT}HAL_Delay(10);`,
      `${INDENT}}`,
      '}',
    ].filter(Boolean).join('\n');

    return [procDefs, tickState, callbacks, mainSrc].filter(Boolean).join('\n\n') + '\n';
  },

  // ── statements ──
  delay: (ms) => `HAL_Delay(${ms});`,
  repeat: (n, body) =>
    `for (uint32_t _i = 0; _i < ${n}u; _i++) {\n${indentBody(body, INDENT)}\n}`,
  ifThen: (cond, then, els) => {
    let out = `if (${cond}) {\n${indentBody(then, INDENT)}\n}`;
    if (els) out += ` else {\n${indentBody(els, INDENT)}\n}`;
    return out;
  },
  waitUntil: (cond) =>
    `while (!(${cond})) { HAL_Delay(20); }`,

  doWrite: (ch, lvl) => {
    const p = stmPin(ch);
    if (!p) return `/* unknown channel ${ch} */`;
    return `HAL_GPIO_WritePin(${p.port}, GPIO_PIN_${p.pin}, GPIO_PIN_${lvl === 'HIGH' ? 'SET' : 'RESET'});  /* ${ch} */`;
  },
  aoWrite: (ch, v) => {
    const m = /^AO(\d+)$/.exec(ch);
    const idx = m ? Number(m[1]) : 0;
    if (idx < 2) {
      const dacCh = idx === 0 ? 'DAC_CHANNEL_1' : 'DAC_CHANNEL_2';
      return `HAL_DAC_SetValue(&hdac, ${dacCh}, DAC_ALIGN_12B_R, (uint32_t)((${v}) * 4095.0f / 5.0f));  /* ${ch} */`;
    }
    return `/* ${ch} via PWM TIM3 — implement __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_${idx}, ...) */\n` +
           `__HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_${idx}, (uint32_t)((${v}) * 1000.0f / 5.0f));`;
  },
  ifChannelThen: (ch, lvl, body) => {
    const p = stmPin(ch);
    const cond = p
      ? `HAL_GPIO_ReadPin(${p.port}, GPIO_PIN_${p.pin}) == GPIO_PIN_${lvl === 'HIGH' ? 'SET' : 'RESET'}`
      : `/* unknown ${ch} */ 0`;
    return `if (${cond}) {  /* ${ch} */\n${indentBody(body, INDENT)}\n}`;
  },

  logTdms: (name, v) =>
    `{ char _buf[64]; int _n = snprintf(_buf, sizeof _buf, "TDMS,${name},%.4f\\r\\n", (float)(${v}));\n` +
    `  HAL_UART_Transmit(&huart2, (uint8_t*)_buf, _n, HAL_MAX_DELAY); }`,
  publishMqtt: (topic, payload) =>
    `/* TODO: MQTT publish to "${topic}". Wire up lwIP + MQTT-C. */\n` +
    `{ char _buf[80]; int _n = snprintf(_buf, sizeof _buf, "MQTT[${topic}] %s\\r\\n", (const char*)(${payload}));\n` +
    `  HAL_UART_Transmit(&huart2, (uint8_t*)_buf, _n, HAL_MAX_DELAY); }`,
  alarm: (via, msg) =>
    `{ const char* _m = "ALARM[${via}] ${msg.replace(/"/g, '\\"')}\\r\\n";\n` +
    `  HAL_UART_Transmit(&huart2, (uint8_t*)_m, strlen(_m), HAL_MAX_DELAY); }`,
  bitResult: (v, val) =>
    `{ char _buf[48]; int _n = snprintf(_buf, sizeof _buf, "BIT ${v} = %.3f\\r\\n", (float)(${val}));\n` +
    `  HAL_UART_Transmit(&huart2, (uint8_t*)_buf, _n, HAL_MAX_DELAY); }`,

  varSet: (name, v) => `${name} = (float)(${v});`,
  procCall: (name) => `${name}();`,

  // ── expressions ──
  aiRead: (ch) => {
    const m = /^AI(\d+)$/.exec(ch);
    const idx = m ? Number(m[1]) : 0;
    return `({ ADC_ChannelConfTypeDef _c={.Channel=ADC_CHANNEL_${idx},.Rank=1,.SamplingTime=ADC_SAMPLETIME_15CYCLES};\n` +
           `   HAL_ADC_ConfigChannel(&hadc1,&_c); HAL_ADC_Start(&hadc1);\n` +
           `   HAL_ADC_PollForConversion(&hadc1, 10);\n` +
           `   (float)HAL_ADC_GetValue(&hadc1) * (3.3f/4095.0f); })  /* ${ch} */`;
  },
  diRead: (ch) => {
    const p = stmPin(ch);
    return p
      ? `(HAL_GPIO_ReadPin(${p.port}, GPIO_PIN_${p.pin}) == GPIO_PIN_SET)  /* ${ch} */`
      : `0  /* unknown ${ch} */`;
  },
  sensorRead: (sensor, ch) =>
    `nexys_sensor_${sensor}(${ch})  /* TODO: link real driver */`,

  scaleLinear: (x, a, b) => `((${a}f) * (${x}) + (${b}f))`,
  computeRms: (sig, n) => `nexys_rms((float)(${sig}), ${n})`,
  lpf: (sig, hz) => `nexys_lpf((float)(${sig}), ${hz}f)`,
  thresholdCheck: (v, lo, hi) => `((${v}) >= (${lo}f) && (${v}) <= (${hi}f))`,

  num: (n) => Number.isInteger(n) ? `${n}` : `${n}f`,
  bool: (v) => v ? '1' : '0',
  text: (s) => JSON.stringify(s),
  varGet: (name) => name,

  arith: (op, a, b) => {
    switch (op) {
      case 'MINUS':    return `((${a}) - (${b}))`;
      case 'MULTIPLY': return `((${a}) * (${b}))`;
      case 'DIVIDE':   return `((${a}) / (${b}))`;
      case 'POWER':    return `powf(${a}, ${b})`;
      default:         return `((${a}) + (${b}))`;
    }
  },
  compare: (op, a, b) => {
    const map: Record<string, string> = { EQ: '==', NEQ: '!=', LT: '<', LTE: '<=', GT: '>', GTE: '>=' };
    return `((${a}) ${map[op] ?? '=='} (${b}))`;
  },
  logicOp: (op, a, b) => `((${a}) ${op === 'OR' ? '||' : '&&'} (${b}))`,

  procDef: (name, body) =>
    `static void ${name}(void) {\n${indentBody(body, INDENT)}\n}`,
};

export function generateStm32(json: WorkspaceJSON): string {
  return walkWorkspace(json, stm32Emitter);
}
