"""nexys — runtime SDK for code generated by Nexys Blockly Studio.

The visual editor emits Python that calls into this package:

    import nexys
    nexys.init(target="ni-pxie", backend="nidaqmx", device="PXI1Slot2")
    nexys.tdms_open("run.tdms")

    def loop_0():
        nexys.channels.do_write('DO0', 'HIGH')
        v = nexys.channels.ai_read('AI0')
        nexys.output.log_tdms('bit_ai0', v)

    def main():
        nexys.timing.loop_every(50, loop_0)

Backends:
  * sim (default) — runs anywhere, no hardware; synthetic signals.
  * ni            — real NI hardware via nidaqmx  (pip install nexys-sdk[ni]).

TDMS output is a genuine TDMS 2.0 binary file (see nexys.tdms), byte-compatible
with LabVIEW / DIAdem / npTDMS.
"""
from __future__ import annotations

from . import channels, interfaces, output, selftest, signal, timing, tdms
from ._core import (
    config,
    get_backend,
    init,
    tdms_close,
    tdms_open,
    tdms_session,
)

__all__ = [
    "init",
    "tdms_open",
    "tdms_close",
    "tdms_session",
    "config",
    "get_backend",
    "channels",
    "timing",
    "signal",
    "output",
    "tdms",
    "interfaces",
    "selftest",
]

__version__ = "0.1.0"
