'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { toast } from 'sonner';

import { TopBar } from '@/components/top-bar';
import { ToolboxPanel } from '@/components/toolbox-panel';
import { WorkspacePanel, type WorkspaceHandle } from '@/components/workspace-panel';
import { RightPanel } from '@/components/right-panel';
import { StatusBar } from '@/components/status-bar';
import { DeployDialog } from '@/components/deploy-dialog';
import { WelcomeDialog } from '@/components/welcome-dialog';
import { ResizeHandle } from '@/components/resize-handle';
import { ModuleDialog } from '@/components/module-dialog';

import { MOCK_DEVICES } from '@/lib/mock-devices';
import type { Device } from '@/lib/types';
import { TEMPLATES, findTemplate } from '@/lib/templates';
import { SimRunner } from '@/lib/simulator/runner';
import type { SimSnapshot } from '@/lib/simulator/types';
import { useTheme } from '@/lib/theme';
import { type Bindings, type Inputs } from '@/lib/hardware/devices';
import {
  DEFAULT_LAYOUT, deriveBindings, type WiringLayout,
} from '@/lib/hardware/wiring-state';
import { TARGETS, DEFAULT_TARGET_ID, findTarget } from '@/lib/targets';
import {
  getModules, setModules, subscribe as subscribeModules, type ModuleDef,
} from '@/lib/blockly/module-store';

const WELCOME_KEY = 'nexys.welcome.dismissed.v1';
const SAVE_KEY = 'nexys.workspace.v1';
const INITIAL_CODE = `# Generated by Nexys Blockly Studio
# Loading workspace…
import nexys
`;

interface SavedWorkspace {
  templateId: string;
  workspaceJson: unknown;
  savedAt: string;
  bindings?: Bindings;       // legacy — kept for back-compat
  wiringLayout?: WiringLayout;
  editedPython?: string | null;
  modules?: ModuleDef[];
}

function loadSavedWorkspace(): SavedWorkspace | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = localStorage.getItem(SAVE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (!parsed?.workspaceJson) return null;
    return parsed as SavedWorkspace;
  } catch {
    return null;
  }
}

export default function Page() {
  // ----- workspace / code state -----
  const [pythonCode, setPythonCode] = useState<string>(INITIAL_CODE);
  const [workspaceJson, setWorkspaceJson] = useState<unknown>({});
  const [selectedDeviceId, setSelectedDeviceId] = useState<string>(MOCK_DEVICES[0].id);
  const [activeTemplateId, setActiveTemplateId] = useState<string>('bit_sequence');
  const [unsaved, setUnsaved] = useState(false);
  const [lastChangeAt, setLastChangeAt] = useState<string | null>(null);
  const emitCountRef = useRef(0);

  // ----- dialogs -----
  const [deployOpen, setDeployOpen] = useState(false);
  const [welcomeOpen, setWelcomeOpen] = useState(false);

  // ----- theme -----
  const { mode: themeMode, resolved: themeResolved, setMode: setThemeMode } = useTheme();

  // ----- right panel width (user-resizable) -----
  const [rightPanelWidth, setRightPanelWidth] = useState(640);

  // ----- left toolbox panel collapse -----
  const [toolboxCollapsed, setToolboxCollapsed] = useState(false);

  // ----- compile target (RPi / Jetson / Arduino / STM32) -----
  const [activeTargetId, setActiveTargetId] = useState<string>(DEFAULT_TARGET_ID);
  const activeTarget = useMemo(
    () => findTarget(activeTargetId) ?? TARGETS[0],
    [activeTargetId]
  );

  // ----- modules (Sub-VIs) -----
  const [moduleList, setModuleList] = useState<ModuleDef[]>(getModules());
  const [moduleDialogOpen, setModuleDialogOpen] = useState(false);
  const [pendingModuleBlockCount, setPendingModuleBlockCount] = useState(0);
  useEffect(() => {
    const unsub = subscribeModules(() => setModuleList(getModules()));
    return () => { unsub(); };
  }, []);

  const handleRequestMakeModule = useCallback(() => {
    const ws = wsRef.current;
    if (!ws) return;
    if (!ws.hasSelection()) {
      toast.error('블록을 먼저 선택하세요', {
        description: '워크스페이스에서 묶을 블록(맨 위 블록)을 클릭한 뒤 Make Module',
        duration: 2600,
      });
      return;
    }
    setPendingModuleBlockCount(1);
    setModuleDialogOpen(true);
  }, []);

  const handleConfirmModule = useCallback((name: string) => {
    const def = wsRef.current?.makeModuleFromSelection(name);
    if (def) {
      const paramNote = def.params?.length
        ? ` · 입력 ${def.params.length}개 (${def.params.map(p => p.name).join(', ')})`
        : '';
      toast.success(`Module "${def.name}" 생성`, {
        description: `${def.blockCount}개 블록 묶음${paramNote} · Modules 카테고리에서 재사용`,
        duration: 3000,
      });
    } else {
      toast.error('모듈 생성 실패', { description: '선택된 블록을 다시 확인하세요', duration: 2400 });
    }
  }, []);

  const handleRequestUngroup = useCallback(() => {
    const ok = wsRef.current?.ungroupSelectedModule();
    if (ok) {
      toast.success('모듈 펼침', { description: '내부 블록으로 복원되었습니다', duration: 2000 });
    } else {
      toast.error('펼칠 모듈이 선택되지 않음', {
        description: '워크스페이스에서 모듈(▦) 블록을 클릭한 뒤 Ungroup',
        duration: 2600,
      });
    }
  }, []);

  // ----- simulator -----
  const runnerRef = useRef<SimRunner | null>(null);
  if (!runnerRef.current) runnerRef.current = new SimRunner();
  const [snapshot, setSnapshot] = useState<SimSnapshot>(() => runnerRef.current!.getSnapshot());
  const [forcedTab, setForcedTab] = useState<'code' | 'runtime' | 'hardware' | 'devices' | null>(null);

  useEffect(() => {
    const unsub = runnerRef.current!.subscribe(setSnapshot);
    return () => { unsub(); };
  }, []);

  // ----- hardware wiring layout (devices + wires) and user inputs -----
  const [wiringLayout, setWiringLayout] = useState<WiringLayout>(DEFAULT_LAYOUT);
  const [inputs, setInputs] = useState<Inputs>({});

  // bindings are derived from wires — single source of truth is the layout
  const bindings: Bindings = useMemo(() => deriveBindings(wiringLayout), [wiringLayout]);

  // push bindings to runner whenever the derived map changes
  useEffect(() => {
    runnerRef.current?.setBindings(bindings);
  }, [bindings]);

  const handleLayoutChange = useCallback((next: WiringLayout) => {
    setWiringLayout(next);
  }, []);

  const handleInputChange = useCallback((channel: string, value: number | boolean) => {
    setInputs(prev => ({ ...prev, [channel]: value }));
    runnerRef.current?.setInput(channel, value);
  }, []);

  // ----- workspace handle (for templates) -----
  const wsRef = useRef<WorkspaceHandle>(null);

  // ----- welcome modal: show on first visit only -----
  useEffect(() => {
    try {
      if (!localStorage.getItem(WELCOME_KEY)) {
        setWelcomeOpen(true);
      }
    } catch {
      setWelcomeOpen(true);
    }
  }, []);
  const dismissWelcome = (open: boolean) => {
    setWelcomeOpen(open);
    if (!open) {
      try { localStorage.setItem(WELCOME_KEY, '1'); } catch {}
    }
  };

  // ----- derived -----
  const activeTemplate = useMemo(
    () => findTemplate(activeTemplateId) ?? TEMPLATES[0],
    [activeTemplateId]
  );
  const workspaceName = activeTemplate.name;
  const selectedDevice: Device =
    MOCK_DEVICES.find(d => d.id === selectedDeviceId) ?? MOCK_DEVICES[0];

  // ----- callbacks -----
  const [codeRegenAt, setCodeRegenAt] = useState<string | null>(null);
  const [codeRegenCount, setCodeRegenCount] = useState(0);
  const [editedPython, setEditedPython] = useState<string | null>(null);

  const handleCodeChange = useCallback((code: string) => {
    setPythonCode(code);
    setCodeRegenAt(new Date().toISOString());
    setCodeRegenCount(c => c + 1);
    emitCountRef.current += 1;
    // First emit is the initial workspace load — don't mark as unsaved.
    if (emitCountRef.current > 1) {
      setUnsaved(true);
      setLastChangeAt(new Date().toISOString());
    }
  }, []);

  const handleWorkspaceChange = useCallback((json: unknown) => {
    setWorkspaceJson(json);
  }, []);

  const handleSave = () => {
    const json = wsRef.current?.getWorkspaceJson() ?? workspaceJson;
    let persisted = false;
    try {
      const payload: SavedWorkspace = {
        templateId: activeTemplateId,
        workspaceJson: json,
        savedAt: new Date().toISOString(),
        wiringLayout,
        editedPython,
        modules: getModules(),
      };
      localStorage.setItem(SAVE_KEY, JSON.stringify(payload));
      persisted = true;
    } catch {
      /* quota or disabled — fall through silently */
    }
    setUnsaved(false);
    setLastChangeAt(new Date().toISOString());
    toast.success('Workspace saved', {
      description: persisted ? `${workspaceName} · localStorage` : `${workspaceName} · in-memory only`,
      duration: 2000,
    });
  };

  const handleWorkspaceReady = useCallback(() => {
    const saved = loadSavedWorkspace();
    if (!saved || !wsRef.current) return;
    // Modules MUST be registered before the workspace JSON (which may contain
    // module blocks) is loaded — setModules fires the panel's subscription
    // which re-registers the block types synchronously.
    if (saved.modules?.length) setModules(saved.modules);
    wsRef.current.loadTemplate(saved.workspaceJson);
    setActiveTemplateId(saved.templateId);
    if (saved.wiringLayout) setWiringLayout(saved.wiringLayout);
    if (saved.editedPython !== undefined) setEditedPython(saved.editedPython);
    emitCountRef.current = 0;
    setUnsaved(false);
    setLastChangeAt(saved.savedAt);
    toast.success('Restored last session', {
      description: `${saved.templateId} · ${new Date(saved.savedAt).toLocaleString()}`,
      duration: 2200,
    });
  }, []);

  const handlePickTemplate = (id: string) => {
    const t = findTemplate(id);
    if (!t || !wsRef.current) return;
    runnerRef.current?.reset();
    wsRef.current.loadTemplate(t.state);
    setActiveTemplateId(id);
    // Auto-apply the template's recommended wiring layout if present
    if (t.wiringLayout) {
      setWiringLayout(t.wiringLayout);
      // clear stale user inputs for newly unbound channels
      setInputs({});
    }
    // Reset emit counter so the auto-emit from template load doesn't mark unsaved.
    emitCountRef.current = 0;
    setUnsaved(false);
    setLastChangeAt(null);
    toast.success(`Loaded "${t.name}"`, {
      description: `${t.description}${t.wiringLayout ? ' · wiring updated' : ''}`,
      duration: 2500,
    });
  };

  const handlePickTarget = (id: string) => {
    const t = findTarget(id);
    if (!t) return;
    setActiveTargetId(id);
    // discard any manual python edits — they don't make sense in a new language
    setEditedPython(null);
    toast.success(`Target → ${t.name}`, {
      description: `${t.description} · ${t.framework}`,
      duration: 2200,
    });
  };

  const handleRun = () => {
    const json = wsRef.current?.getWorkspaceJson() ?? workspaceJson;
    runnerRef.current?.start(json);
    setForcedTab('runtime');
    toast.success('Simulation started', {
      description: 'Virtual runtime · no hardware needed',
      duration: 1500,
    });
  };

  const handleStop = () => {
    runnerRef.current?.stop();
  };

  const handleReset = () => {
    runnerRef.current?.reset();
  };

  const running = snapshot.status === 'running';

  return (
    <div className="flex h-screen flex-col">
      <TopBar
        workspaceName={workspaceName}
        unsaved={unsaved}
        running={running}
        templates={TEMPLATES}
        activeTemplateId={activeTemplateId}
        targets={TARGETS}
        activeTargetId={activeTargetId}
        themeMode={themeMode}
        onSave={handleSave}
        onDeploy={() => setDeployOpen(true)}
        onRun={handleRun}
        onStop={handleStop}
        onPickTemplate={handlePickTemplate}
        onPickTarget={handlePickTarget}
        onHelp={() => setWelcomeOpen(true)}
        onPickTheme={setThemeMode}
      />

      <main className="flex flex-1 overflow-hidden">
        <ToolboxPanel
          activeModule="defense"
          collapsed={toolboxCollapsed}
          onToggleCollapse={() => setToolboxCollapsed(c => !c)}
        />

        <WorkspacePanel
          ref={wsRef}
          onCodeChange={handleCodeChange}
          onWorkspaceChange={handleWorkspaceChange}
          onReady={handleWorkspaceReady}
          theme={themeResolved}
          target={activeTarget}
          onRequestMakeModule={handleRequestMakeModule}
          onRequestUngroup={handleRequestUngroup}
        />

        <ResizeHandle
          currentWidth={rightPanelWidth}
          min={320}
          max={1100}
          onResize={setRightPanelWidth}
          side="right"
        />

        <RightPanel
          code={pythonCode}
          devices={MOCK_DEVICES}
          selectedDeviceId={selectedDeviceId}
          onSelectDevice={setSelectedDeviceId}
          snapshot={snapshot}
          onRun={handleRun}
          onStop={handleStop}
          onReset={handleReset}
          forcedTab={forcedTab}
          onTabConsumed={() => setForcedTab(null)}
          theme={themeResolved}
          codeRegenCount={codeRegenCount}
          codeRegenAt={codeRegenAt}
          editedCode={editedPython}
          onCommitEdit={setEditedPython}
          codeLanguage={activeTarget.monacoLang}
          targetName={activeTarget.name}
          targetId={activeTarget.id}
          bindings={bindings}
          inputs={inputs}
          onInputChange={handleInputChange}
          layout={wiringLayout}
          onLayoutChange={handleLayoutChange}
          width={rightPanelWidth}
        />
      </main>

      <StatusBar
        mode="Defense"
        device={selectedDevice}
        unsaved={unsaved}
        lastChangeAt={lastChangeAt}
      />

      <DeployDialog
        open={deployOpen}
        onOpenChange={setDeployOpen}
        devices={MOCK_DEVICES}
        initialDeviceId={selectedDeviceId}
        workspaceName={workspaceName}
        workspaceJson={workspaceJson}
        pythonCode={editedPython ?? pythonCode}
        target={activeTarget}
      />

      <WelcomeDialog
        open={welcomeOpen}
        onOpenChange={dismissWelcome}
        onTryDemo={handleRun}
      />

      <ModuleDialog
        open={moduleDialogOpen}
        onOpenChange={setModuleDialogOpen}
        blockCount={pendingModuleBlockCount}
        onConfirm={handleConfirmModule}
      />
    </div>
  );
}
